### ISSUE TITLE
Play 1.7.0 - Groovy templates does not support the #{extends ...} decorator

### ISSUE THREAD

**Issue by ehud-eshet** [playframework/play1#1412]
### Expected Behavior

Groovy templates with #{extends} should be supported as documented in [Play 1.2.5 documentation](https://www.playframework.com/documentation/1.2.5/templates). I did not find a more recent documentation.
Same templates works fine on Play 1.5.3 on JDK 11.0.10.

### Actual Behavior

When executing play precompile, I get the following error:
```
Template compilation error (In /app/views/MyAccountsController/myProfile.html around line 0)
The template /app/views/MyAccountsController/myProfile.html does not compile : Unexpected input: '{'

play.exceptions.TemplateCompilationException: Unexpected input: '{'
        at play.templates.GroovyTemplate.compile(GroovyTemplate.java:218) ~[play-1.7.0.jar:?]
        at play.templates.TemplateLoader.scan(TemplateLoader.java:281) ~[play-1.7.0.jar:?]
        at play.templates.TemplateLoader.scan(TemplateLoader.java:293) ~[play-1.7.0.jar:?]
        at play.templates.TemplateLoader.scan(TemplateLoader.java:293) ~[play-1.7.0.jar:?]
        at play.templates.TemplateLoader.getAllTemplate(TemplateLoader.java:224) ~[play-1.7.0.jar:?]
        at play.Play.preCompile(Play.java:640) ~[play-1.7.0.jar:?]
        at play.Play.init(Play.java:325) ~[play-1.7.0.jar:?]
        at play.server.Server.main(Server.java:164) ~[play-1.7.0.jar:?]
~        _            _
~  _ __ | | __ _ _  _| |
~ | '_ \| |/ _' | || |_|
~ |  __/|_|\____|\__ (_)
~ |_|            |__/
~
~ play! 1.7.0, https://www.playframework.com
~ framework ID is production
~
~ using java version "17.0.3"
```

The template (myProfile.html) starts with the following text:
```
#{extends '/templates/new_base.html'/}

#{set 'head'}
<link href="#{pubcache 'na-v2/dist/css/application.css' /}" rel="stylesheet" media="all">
<style xmlns="http://www.w3.org/1999/html">
    #cancelEditGADetailsButton  {
        float: right;
    }

    .settingsTable td {
        width:50%;
    }
    #qrProvidedKey{color:red;}

</style>
#{/set}
```

**Comment by ehud-eshet** [comment]
After a lot of divide-and-conquer, I managed to identify the problematic template line.
```
#{widgets.button2  onClick:'getCodeForPhone()' ,id:'getCodeForPhone', color:"blue" ,text:'Get Code', ,buttonSize:'small'/}
```
There is a redundant comma before `buttonSize`.
Play 1.5.3 with Groovy 2.5.3 was more tolerant.
Play 1.7.0 with Groovy 3.0.10 fails and the error message does not help all.
The issue can be closed.

**Comment by xael-fry** [comment]
Close it thanks
